name: Publish Docker image
permissions: write-all
on:
  release:
    types:
      - published
jobs:
  publish:
    name: Publish Docker image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3.5.3
      - name: Login to Docker registry
        uses: docker/login-action@v2.2.0
        with:
          registry: ghcr.io
          password: ${{ secrets.GITHUB_TOKEN }}
          username: ${{ github.actor }}
      - name: Build and publish Docker image
        uses: docker/build-push-action@v4.1.1
        with:
          context: .
          push: true
          tags: |
            ghcr.io/radekmie/changestream-to-redis:latest
            ghcr.io/radekmie/changestream-to-redis:${{ github.event.release.tag_name }}
